"""
Django settings for subasta_frutas project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-namtjev)!xugm#-r0n@##^6rt=br%()(uxq6_!9z8vjj#nkqtd'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

# =============================================================================
# APLICACIONES INSTALADAS
# =============================================================================
INSTALLED_APPS = [
    # Aplicaciones de Django por defecto
    'django.contrib.admin',         # Panel de administración
    'django.contrib.auth',          # Sistema de autenticación
    'django.contrib.contenttypes',  # Framework de tipos de contenido
    'django.contrib.sessions',      # Manejo de sesiones
    'django.contrib.messages',      # Framework de mensajes
    'django.contrib.staticfiles',   # Manejo de archivos estáticos
    
    # Aplicaciones de terceros
    'rest_framework',               # Django REST Framework para la API
    'rest_framework_simplejwt',     # JWT para autenticación
    'corsheaders',                  # Manejo de CORS para peticiones del frontend
    
    # Aplicaciones locales del proyecto
    'clientes',                     # Módulo de gestión de clientes
    'usuarios',                     # Módulo de gestión de usuarios
    'modulo_packing',               # Módulo de packing (proyecciones semanales)
]

# =============================================================================
# MIDDLEWARE
# Capas de procesamiento de peticiones/respuestas
# =============================================================================
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',           # Seguridad general
    'corsheaders.middleware.CorsMiddleware',                   # CORS (debe ir antes de CommonMiddleware)
    'django.contrib.sessions.middleware.SessionMiddleware',    # Sesiones
    'django.middleware.common.CommonMiddleware',               # Operaciones comunes
    'django.middleware.csrf.CsrfViewMiddleware',               # Protección CSRF
    'django.contrib.auth.middleware.AuthenticationMiddleware', # Autenticación
    'django.contrib.messages.middleware.MessageMiddleware',    # Mensajes
    'django.middleware.clickjacking.XFrameOptionsMiddleware',  # Protección clickjacking
]

# =============================================================================
# CONFIGURACIÓN DE CORS (Cross-Origin Resource Sharing)
# Permite que el frontend (React, Vue, etc.) haga peticiones a la API
# =============================================================================
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",    # React (Create React App)
    "http://localhost:5173",    # Vite (React, Vue, etc.)
    "http://127.0.0.1:3000",    # Alternativa localhost
    "http://127.0.0.1:5173",    # Alternativa localhost
]

# Permitir envío de cookies/credenciales en peticiones CORS
CORS_ALLOW_CREDENTIALS = True

# =============================================================================
# CONFIGURACIÓN DE DJANGO REST FRAMEWORK
# =============================================================================
REST_FRAMEWORK = {
    # Clases de autenticación por defecto
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    # Clases de permisos por defecto
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    # Paginación automática para listados
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,  # 20 registros por página
}

# =============================================================================
# CONFIGURACIÓN DE JWT (JSON Web Tokens)
# =============================================================================
from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=8),      # Token válido por 8 horas
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),      # Refresh token válido por 7 días
    'ROTATE_REFRESH_TOKENS': True,                    # Rotar refresh tokens
    'BLACKLIST_AFTER_ROTATION': True,                 # Invalidar tokens antiguos
    'AUTH_HEADER_TYPES': ('Bearer',),                 # Tipo de header de autenticación
}

ROOT_URLCONF = 'subasta_frutas.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'subasta_frutas.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
