# Generated by Django 6.0 on 2026-01-19 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0003_cliente_password'),
        ('modulo_packing', '0004_packingimagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subasta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora_inicio', models.DateTimeField(verbose_name='Fecha y hora de inicio')),
                ('fecha_hora_fin', models.DateTimeField(verbose_name='Fecha y hora de finalización')),
                ('precio_base', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio base (monto mínimo inicial)')),
                ('estado', models.CharField(choices=[('PROGRAMADA', 'Programada'), ('ACTIVA', 'Activa'), ('FINALIZADA', 'Finalizada'), ('CANCELADA', 'Cancelada')], default='PROGRAMADA', max_length=20, verbose_name='Estado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('packing_detalle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subasta', to='modulo_packing.packingdetalle', verbose_name='Producción Diaria')),
            ],
            options={
                'verbose_name': 'Subasta',
                'verbose_name_plural': 'Subastas',
                'ordering': ['-fecha_hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto ofertado')),
                ('es_ganadora', models.BooleanField(default=False, verbose_name='Es ganadora')),
                ('fecha_oferta', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora de la oferta')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Versión (control de concurrencia)')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofertas', to='clientes.cliente', verbose_name='Cliente')),
                ('subasta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofertas', to='subastas.subasta', verbose_name='Subasta')),
            ],
            options={
                'verbose_name': 'Oferta',
                'verbose_name_plural': 'Ofertas',
                'ordering': ['-monto', '-fecha_oferta'],
                'indexes': [models.Index(fields=['subasta', '-monto'], name='subastas_of_subasta_9a8b11_idx'), models.Index(fields=['cliente', '-fecha_oferta'], name='subastas_of_cliente_15fff1_idx')],
            },
        ),
    ]
