# Generated by Django 6.0 on 2026-01-20 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_packing', '0004_packingimagen'),
        ('subastas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subasta',
            name='packing_detalle',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='subasta', to='modulo_packing.packingdetalle', verbose_name='Producción Diaria'),
        ),
    ]
