# Generated by Django 6.0.1 on 2026-02-11 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_packing', '0004_packingimagen'),
        ('subastas', '0002_change_packing_detalle_on_delete_to_protect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subasta',
            name='packing_detalle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subastas', to='modulo_packing.packingdetalle', verbose_name='Producción Diaria'),
        ),
    ]
