# Generated by Django 6.0.1 on 2026-02-18 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subastas', '0003_change_packing_detalle_to_fk'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionSubasta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('antisniping_habilitado', models.BooleanField(default=True, verbose_name='Extensión automática habilitada')),
                ('antisniping_umbral_segundos', models.PositiveIntegerField(default=120, help_text='Si quedan menos de X segundos y alguien puja, se extiende el tiempo.', verbose_name='Umbral de activación (segundos)')),
                ('antisniping_extension_segundos', models.PositiveIntegerField(default=120, help_text='Cuántos segundos se agregan al tiempo de fin cuando se activa.', verbose_name='Tiempo a agregar (segundos)')),
                ('antisniping_max_extensiones', models.PositiveIntegerField(default=5, help_text='Número máximo de veces que se puede extender. 0 = sin límite.', verbose_name='Máximo de extensiones')),
            ],
            options={
                'verbose_name': 'Configuración de Subastas',
                'verbose_name_plural': 'Configuración de Subastas',
            },
        ),
        migrations.AddField(
            model_name='subasta',
            name='extensiones_realizadas',
            field=models.PositiveIntegerField(default=0, verbose_name='Extensiones de tiempo realizadas'),
        ),
    ]
