# Generated by Django 6.0.1 on 2026-03-04 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subastas', '0004_add_configuracion_subasta_y_extensiones'),
    ]

    operations = [
        migrations.AddField(
            model_name='oferta',
            name='kilos_solicitados',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cantidad de kilos que el cliente desea comprar (puede ser mayor a los disponibles)', max_digits=10, null=True, verbose_name='Kilos solicitados'),
        ),
    ]
