# Generated by Django 6.0 on 2026-01-07 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre de la empresa')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoFruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del tipo de fruta')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Tipo de Fruta',
                'verbose_name_plural': 'Tipos de Fruta',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Packing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_proyeccion', models.DateField(verbose_name='Fecha de proyección (inicio de semana)')),
                ('kg_total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='KG Total')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packings', to='modulo_packing.empresa', verbose_name='Empresa')),
                ('tipo_fruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packings', to='modulo_packing.tipofruta', verbose_name='Tipo de Fruta')),
            ],
            options={
                'verbose_name': 'Packing',
                'verbose_name_plural': 'Packings',
                'ordering': ['-fecha_proyeccion'],
                'unique_together': {('empresa', 'tipo_fruta', 'fecha_proyeccion')},
            },
        ),
        migrations.CreateModel(
            name='PackingDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('lunes', 'Lunes'), ('martes', 'Martes'), ('miercoles', 'Miércoles'), ('jueves', 'Jueves'), ('viernes', 'Viernes'), ('sabado', 'Sábado'), ('domingo', 'Domingo')], max_length=10, verbose_name='Día')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('py', models.CharField(max_length=50, verbose_name='PY')),
                ('kg', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Kilogramos')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('packing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='modulo_packing.packing', verbose_name='Packing')),
            ],
            options={
                'verbose_name': 'Detalle de Packing',
                'verbose_name_plural': 'Detalles de Packing',
                'ordering': ['fecha'],
            },
        ),
    ]
