# Generated by Django 6.0 on 2026-01-13 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_packing', '0002_alter_packingsemanal_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packingdetalle',
            name='kg',
        ),
        migrations.AlterField(
            model_name='packingdetalle',
            name='py',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Kilogramos (PY)'),
        ),
    ]
