# Generated by Django 6.0.1 on 2026-01-18 02:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_packing', '0003_remove_packingdetalle_kg_alter_packingdetalle_py'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackingImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='packing/%Y/%m/', verbose_name='Imagen')),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descripción')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de subida')),
                ('packing_semanal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='modulo_packing.packingsemanal', verbose_name='Packing Semanal')),
                ('packing_tipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='modulo_packing.packingtipo', verbose_name='Tipo de Fruta (opcional)')),
            ],
            options={
                'verbose_name': 'Imagen de Packing',
                'verbose_name_plural': 'Imágenes de Packing',
                'ordering': ['-fecha_subida'],
            },
        ),
    ]
