# Generated by Django 6.0 on 2026-01-07 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruc_dni', models.CharField(max_length=20, unique=True, verbose_name='RUC/DNI')),
                ('nombre_razon_social', models.CharField(max_length=255, verbose_name='Nombre o Razón Social')),
                ('tipo', models.CharField(choices=[('persona_natural', 'Persona Natural'), ('persona_juridica', 'Persona Jurídica')], max_length=20, verbose_name='Tipo')),
                ('sede', models.CharField(max_length=100, verbose_name='Sede')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('pendiente', 'Pendiente')], default='activo', max_length=20, verbose_name='Estado')),
                ('contacto_1', models.CharField(max_length=150, verbose_name='Contacto 1')),
                ('cargo_1', models.CharField(max_length=100, verbose_name='Cargo')),
                ('numero_1', models.CharField(max_length=20, verbose_name='Número de Teléfono')),
                ('correo_electronico_1', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('contacto_2', models.CharField(blank=True, max_length=150, null=True, verbose_name='Contacto 2')),
                ('cargo_2', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cargo 2')),
                ('numero_2', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número de Teléfono 2')),
                ('correo_electronico_2', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico 2')),
                ('estatus_ficha', models.CharField(choices=[('completa', 'Completa'), ('incompleta', 'Incompleta'), ('en_revision', 'En Revisión')], default='incompleta', max_length=20, verbose_name='Estatus de Ficha')),
                ('confirmacion_correo', models.BooleanField(default=False, verbose_name='Confirmación de Correo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
