# Generated by Django 6.0 on 2026-01-07 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='estado',
            field=models.CharField(choices=[('habilitado', 'Habilitado'), ('deshabilitado', 'Deshabilitado')], default='habilitado', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='estatus_ficha',
            field=models.CharField(choices=[('recepcionado', 'Recepcionado'), ('pendiente', 'Pendiente')], default='pendiente', max_length=20, verbose_name='Estatus de Ficha'),
        ),
    ]
