# Generated by Django 6.0.1 on 2026-01-12 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_cliente_estado_alter_cliente_estatus_ficha'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Contraseña'),
        ),
    ]
