# Generated by Django 6.0.1 on 2026-02-02 17:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilPermiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Perfil')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('es_superusuario', models.BooleanField(default=False, help_text='Un superusuario tiene acceso total a todo el sistema', verbose_name='Es Superusuario')),
                ('permisos', models.JSONField(default=dict, help_text='Estructura: {"modulo": ["permiso1", "permiso2"]}', verbose_name='Permisos')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfiles_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Perfil de Permiso',
                'verbose_name_plural': 'Perfiles de Permisos',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='perfil_permiso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='usuarios.perfilpermiso', verbose_name='Perfil de Permisos'),
        ),
    ]
