# Generated by Django 6.0.1 on 2026-02-16 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_perfilpermiso_perfilusuario_perfil_permiso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilusuario',
            name='es_administrador',
        ),
    ]
