# Generated by Django 6.0.1 on 2026-02-16 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_remove_es_administrador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilusuario',
            name='telefono',
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='dni',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='DNI'),
        ),
    ]
