# Generated by Django 6.0 on 2026-01-07 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre de la empresa')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoFruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del tipo')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Tipo de Fruta',
                'verbose_name_plural': 'Tipos de Fruta',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='PackingSemanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio_semana', models.DateField(verbose_name='Fecha inicio de semana (Lunes)')),
                ('fecha_fin_semana', models.DateField(verbose_name='Fecha fin de semana (Domingo)')),
                ('kg_total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='KG Total (calculado)')),
                ('estado', models.CharField(choices=[('PROYECTADO', 'Proyectado'), ('ACTIVO', 'Activo'), ('CERRADO', 'Cerrado'), ('ANULADO', 'Anulado')], default='PROYECTADO', max_length=20, verbose_name='Estado')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packings_semanales', to='modulo_packing.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Packing Semanal',
                'verbose_name_plural': 'Packings Semanales',
                'ordering': ['-fecha_inicio_semana', 'empresa__nombre'],
                'unique_together': {('empresa', 'fecha_inicio_semana')},
            },
        ),
        migrations.CreateModel(
            name='PackingTipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kg_total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='KG Total')),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], default='ACTIVO', max_length=20, verbose_name='Estado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('packing_semanal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipos', to='modulo_packing.packingsemanal', verbose_name='Packing Semanal')),
                ('tipo_fruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packing_tipos', to='modulo_packing.tipofruta', verbose_name='Tipo de Fruta')),
            ],
            options={
                'verbose_name': 'Packing por Tipo de Fruta',
                'verbose_name_plural': 'Packings por Tipo de Fruta',
                'ordering': ['tipo_fruta__nombre'],
                'unique_together': {('packing_semanal', 'tipo_fruta')},
            },
        ),
        migrations.CreateModel(
            name='PackingDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('LUNES', 'Lunes'), ('MARTES', 'Martes'), ('MIERCOLES', 'Miércoles'), ('JUEVES', 'Jueves'), ('VIERNES', 'Viernes'), ('SABADO', 'Sábado')], max_length=10, verbose_name='Día')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('py', models.CharField(blank=True, default='', max_length=50, verbose_name='PY')),
                ('kg', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Kilogramos')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('packing_tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='modulo_packing.packingtipo', verbose_name='Packing Tipo')),
            ],
            options={
                'verbose_name': 'Detalle de Packing',
                'verbose_name_plural': 'Detalles de Packing',
                'ordering': ['fecha'],
                'unique_together': {('packing_tipo', 'dia')},
            },
        ),
    ]
