# Generated by Django 6.0 on 2026-01-13 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_packing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packingsemanal',
            name='estado',
            field=models.CharField(choices=[('PROYECTADO', 'Proyectado'), ('EN_SUBASTA', 'En Subasta'), ('FINALIZADO', 'Finalizado'), ('ANULADO', 'Anulado')], default='PROYECTADO', max_length=20, verbose_name='Estado'),
        ),
    ]
